const loginFields = [
    {
        labelText: "email",
        labelFor: "email",
        id: "email",
        name: "email",
        type: "text",
        isRequired: true,
        placeholder: "indirizzo email o username",
    },
    {
        labelText: "Password",
        labelFor: "password",
        id: "password",
        name: "password",
        type: "password",
        isRequired: true,
        placeholder: "Password",
    },
];
const doctorFields = [
    {
        labelText: "nome",
        labelFor: "nome",
        id: "nome",
        name: "name",
        type: "text",
        isRequired: false,
        placeholder: "nome",
    },
    {
        labelText: "cognome",
        labelFor: "cognome",
        id: "cognome",
        name: "surname",
        type: "text",
        isRequired: false,
        placeholder: "cognome",
    },
    {
        labelText: "password",
        labelFor: "password",
        id: "password",
        name: "password",
        type: "text",
        isRequired: false,
        placeholder: "password",
    },
    {
        labelText: "email",
        labelFor: "email",
        id: "email",
        name: "email",
        type: "email",
        isRequired: false,
        placeholder: "email",
    },
    {
        labelText: "telefono",
        labelFor: "telefono",
        id: "telefono",
        name: "telefono",
        type: "text",
        isRequired: false,
        placeholder: "telefono",
    },
];
const patientFields = [
    {
        labelText: "nome",
        labelFor: "nome",
        id: "nome",
        name: "name",
        type: "text",
        isRequired: false,
        placeholder: "nome",
    },
    {
        labelText: "cognome",
        labelFor: "cognome",
        id: "cognome",
        name: "surname",
        type: "text",
        isRequired: false,
        placeholder: "cognome",
    },
    {
        labelText: "password",
        labelFor: "password",
        id: "password",
        name: "password",
        type: "text",
        isRequired: false,
        placeholder: "password",
    },
    {
        labelText: "email",
        labelFor: "email",
        id: "email",
        name: "email",
        type: "email",
        isRequired: false,
        placeholder: "email",
    },
    {
        labelText: "telefono",
        labelFor: "telefono",
        id: "telefono",
        name: "telefono",
        type: "text",
        isRequired: false,
        placeholder: "telefono",
    },
    {
        labelText: "dottore",
        labelFor: "dottore",
        id: "dottore",
        name: "doctor",
        type: "text",
        isRequired: false,
        placeholder: "dottore",
    },
];
const reportFields = [
    {
        labelText: "content",
        labelFor: "content",
        id: "content",
        name: "content",
        type: "text",
        isRequired: false,
        placeholder: "content",
    },
    {
        labelText: "field",
        labelFor: "field",
        id: "field",
        name: "field",
        type: "text",
        isRequired: false,
        placeholder: "field",
    },
    {
        labelText: "patient",
        labelFor: "patient",
        id: "patient",
        name: "patient",
        type: "text",
        isRequired: false,
        placeholder: "patient",
    },
    {
        labelText: "doctor",
        labelFor: "doctor",
        id: "doctor",
        name: "doctor",
        type: "text",
        isRequired: false,
        placeholder: "doctor",
    }
]

const examFields = [
    {
        labelText: "content",
        labelFor: "content",
        id: "content",
        name: "content",
        type: "text",
        isRequired: false,
        placeholder: "content",
    },
    {
        labelText: "field",
        labelFor: "field",
        id: "field",
        name: "field",
        type: "text",
        isRequired: false,
        placeholder: "field",
    },
    {
        labelText: "patient",
        labelFor: "patient",
        id: "patient",
        name: "patient",
        type: "text",
        isRequired: false,
        placeholder: "patient",
    },
    {
        labelText: "doctor",
        labelFor: "doctor",
        id: "doctor",
        name: "doctor",
        type: "text",
        isRequired: false,
        placeholder: "doctor",
    },
    {
        labelText: "report",
        labelFor: "report",
        id: "report",
        name: "report",
        type: "text",
        isRequired: false,
        placeholder: "report",
    },
    {
        labelText: "completed",
        labelFor: "completed",
        id: "completed",
        name: "completed",
        type: "text",
        isRequired: false,
        placeholder: "completed",
    }
]


export { loginFields, doctorFields, patientFields, reportFields, examFields };
